server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service

eureka:
  client:
    register-with-eureka: true #se registra como cliente de eureka en el servidor
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
