server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
    data:
      mongodb:
        database: test
        port: 27018


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  zipkin:
    base-url: http://localhost:9411/
    enabled: true


queue:
  movie:
    name: movie-queue
    exchange: movie-exchange
    routing-key: movie
  serie:
    name: serie-queue
    exchange: serie-exchange
    routing-key: serie

eureka:
  client:
    register-with-eureka: true #se registra como cliente de eureka en el servidor
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10




#resilience4j: