server:
  #port: ${PORT:${SERVER_PORT:0}}
  port: 0

spring:
  application:
    name: catalog-service

eureka:
  client:
    register-with-eureka: true #se registra como cliente de eureka en el servidor
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}