server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

