server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      host: 52.202.239.67
      database: test
      port: 27017

queue:
  serie:
    name: serie-queue
    exchange: serie-exchange
    routing-key: serie




eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: movie-service:${random.int}
    preferIpAddress: true
