server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017

  application:
    name: serie-service

  #rabbit
  #zipkin


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: movie-service:${random.int}
    preferIpAddress: true
